In [ ]:
# Implement DFS, BFS for 8-puzzle problem

In [1]:
def bfs (src, target):
    queue = []
    exp = []
    queue.append(src)

    while len(queue) > 0:
        source = queue.pop(0)
        exp.append(source)
        print_puzzel(source)

        if target == source:
            print()
            print("Success")
            return

        pos = find_pos(source, exp)

        for move in pos:
            if move not in exp and move not in queue:
                queue.append(move)

In [4]:
def find_pos (state , visited):
    b = state.index(0)
    directions = []

    if b not in [0,1,2]:
        directions.append("up")
    if b not in [6,7,8]:
        directions.append("down")
    if b not in [0,3,6]:
        directions.append("left")
    if b not in [2,5,8]:
        directions.append("right")  

    moves = []
    for i in directions:
        moves.append(gen(state, i , b))
    return [move for move in moves if move not in visited]  

In [5]:
def gen (state,i,b):

    temp = state.copy()

    if i == "down":
        temp[b+3], temp[b] = temp[b], temp[b+3]
    if i =="up":
        temp[b-3], temp[b] = temp[b], temp[b-3]
    if i == "left":
        temp[b-1], temp[b] = temp[b], temp[b-1]
    if i == "right" :
        temp[b+1] , temp[b] = temp[b], temp[b+1]

    return temp

In [10]:
import numpy as np

def print_puzzel (state):
    print(np.array(state).reshape(3,3))
    print()

In [11]:
src = [1, 2, 3, 4, 5, 6, 0, 7, 8]
target = [1, 2, 3, 4, 5, 6, 7, 8, 0]

print("Initial state: ")
print_puzzel(src)       #initial state
print()

print("Goal state: ")
print_puzzel(target)    #goal state
print()

print("BFS solution:")
bfs(src, target)

Initial state: 
[[1 2 3]
 [4 5 6]
 [0 7 8]]


Goal state: 
[[1 2 3]
 [4 5 6]
 [7 8 0]]


BFS solution:
[[1 2 3]
 [4 5 6]
 [0 7 8]]

[[1 2 3]
 [0 5 6]
 [4 7 8]]

[[1 2 3]
 [4 5 6]
 [7 0 8]]

[[0 2 3]
 [1 5 6]
 [4 7 8]]

[[1 2 3]
 [5 0 6]
 [4 7 8]]

[[1 2 3]
 [4 0 6]
 [7 5 8]]

[[1 2 3]
 [4 5 6]
 [7 8 0]]


Success
